### ISSUE TITLE
Rental jokers crash the game

### ISSUE THREAD

**Issue by DaviAMSilva** [betmma/my_balatro_mods#11]
![20240630160105_1](https://github.com/betmma/my_balatro_mods/assets/53585493/e62b2003-d325-4e77-9912-ef83e5e8d743)
[lovely-2024.06.30-16.37.46.log](https://github.com/user-attachments/files/16045941/lovely-2024.06.30-16.37.46.log)

Hello, I've been playing your mods and have really liked them so far.

Unfortunately it seems that the Voucher Debt Burden causes an issue where whenever you finish a round with with an rental joker it crashes the game with the logs pinned above.

Additionally the jokers don't to have the rental tag found when playing a gold seal deck.

Thankfully i was able to save the run I had by editing the save manually and removing the rental property of the joker i had bought.

**Comment by DaviAMSilva** [comment]
Also it seems that a similar crash is happening to perishable jokers. When first bought they display the ERROR on the remaining tally and crash when round beings

**Comment by betmma** [comment]
You are using SMOD 0.9.8 right, actually I haven't tested 0.9.8 compatibility for some days. Since latest SMOD 1.0.0 supports 0.9.8 mods, and according to a poll in discord days ago, 80% of people are using SMOD 1.0.0, I don't think I still need to support 0.9.8 version.

**Comment by DaviAMSilva** [comment]
I see. Thanks for the response.

I didn't know the most compatible version was the direct download from main, especially since there isn't an 1.0.0 GitHub release yet. I have already updated to the new version and it should probably stop happening now.
