### ISSUE TITLE
4D Booster Packs causing crashes later in a run

### ISSUE THREAD

**Issue by gtgeli** [betmma/my_balatro_mods#2]
Like title says, 4D booster pack is leading to crashes, not sure if it’s an incompatibility with another mod I am using but the Lua error says that it is attempting to index a nil value and looks like it is trying to refresh to a booster pack that has either been tagged as “USED” or does not exist. Will try to get an error log later.

**Comment by gtgeli** [comment]
Actually this might have been because of the decimal price issue you fixed a few days back, I'll update my files and test again.

**Comment by gtgeli** [comment]
![IMG_4565](https://github.com/betmma/my_balatro_mods/assets/169810575/d48fdf72-140d-424f-8c5a-e9be5ffa573e)
So I’m playing on Steam Deck and this was all I could get so I apologize, but I can try recreating it on my PC if more info is needed.

**Comment by Ardub23** [comment]
I've had a similar crash when the game tries to go to the shop after cashing out from the Ante 7 boss. When I removed BetmmaVouchers from the mod folder and tried again, I found that the Ante 8 boss was the Vermillion Trident from [Bunco](https://github.com/Firch/Bunco), which disables shops for the whole ante. I guess Vermillion Trident just skips initializing the shop altogether, but 3D Boosters is assuming there's a shop to modify.

I haven't had crashes with The Miser, a Bunco boss that skips the shop after it's defeated, though I'm not 100% sure I've ever faced it with 3D Boosters.

**Comment by betmma** [comment]
> I've had a similar crash when the game tries to go to the shop after cashing out from the Ante 7 boss. When I removed BetmmaVouchers from the mod folder and tried again, I found that the Ante 8 boss was the Vermillion Trident from [Bunco](https://github.com/Firch/Bunco), which disables shops for the whole ante. I guess Vermillion Trident just skips initializing the shop altogether, but 3D Boosters is assuming there's a shop to modify.
> 
> I haven't had crashes with The Miser, a Bunco boss that skips the shop after it's defeated, though I'm not 100% sure I've ever faced it with 3D Boosters.

Thanks, your analysis is correct and it will be fixed in the next release
