### ISSUE TITLE
Art Gallery's −1 Ante can delay winning after final Boss Blind

### ISSUE THREAD

**Issue by Ardub23** [betmma/my_balatro_mods#4]
When defeating the final Boss Blind with the Art Gallery voucher redeemed, its effect takes place before the game determines that the run's been won. If it gives −1 Ante, you'll be in the anticlimactic situation of having to replay the Ante and defeat another final Boss Blind to secure the victory.

**Comment by betmma** [comment]
I should call end_round_ref before reducing ante. Fixed
